### ISSUE TITLE
Is there block minting rewards pallet?

### ISSUE THREAD

**Issue by zikunfan** [substrate-developer-hub/substrate-node-template#20]
Hi guys, 
I am trying to adding *block minting reward* function to my own chain, I am using the default `staking pallet` like this: 
```rust
pallet_staking_reward_curve::build! {
	const REWARD_CURVE: PiecewiseLinear<'static> = curve!(
		min_inflation: 0_025_000,
		max_inflation: 0_100_000,
		ideal_stake: 0_500_000,
		falloff: 0_050_000,
		max_piece_count: 40,
		test_precision: 0_005_000,
	);
}

parameter_types! {
	// Six sessions in an era (6 sessions).
	pub const SessionsPerEra: SessionIndex = 6;
	// 28 eras for unbonding (7 days).
	pub const BondingDuration: staking::EraIndex = 28;
	// 28 eras in which slashes can be cancelled (7 days).
	pub const SlashDeferDuration: staking::EraIndex = 28;
	pub const RewardCurve: &'static PiecewiseLinear<'static> = &REWARD_CURVE;
}

/* snippet */

impl staking::Trait for Runtime {
	type Currency = Balances;
	type Time = Timestamp;

	type CurrencyToVote = CurrencyToVoteHandler;
	type RewardRemainder = Treasury;
	type Event = Event;
	type Slash = Treasury;
	type Reward = ();
	type SessionsPerEra = SessionsPerEra;
	type BondingDuration = BondingDuration;
	type SlashDeferDuration = SlashDeferDuration;

	// A majority of the council can cancel the slash.
	// TODO: add slash cancellation via collective pallet
	type SlashCancelOrigin = collective::EnsureProportionAtLeast<_1, _2, AccountId, CouncilCollective>;
	type SessionInterface = Self;
	type RewardCurve = RewardCurve;
}
```
and my *chain constants* are:
> 1 session = 10 block, 1 era = 2 session (for test)

But I found there has **no block rewards** in the end of each era. Am I writing the right way? or should I import more `pallet`?

**Comment by zikunfan** [comment]
it shows like this in `apps.js`

<img width="725" alt="WechatIMG4" src="https://user-images.githubusercontent.com/10335300/72275400-ce11e780-3668-11ea-8aa3-96f90ec93b27.png">

**Comment by JoshOrndorff** [comment]
Hi @zikunfan,

Have you read about the [rewards calculation](https://substrate.dev/rustdocs/master/pallet_staking/index.html#reward-calculation) in the staking pallet? Are you using PalletAuthorship to award point sand connecting it to the Staking module as demonstrated [here](https://github.com/paritytech/substrate/blob/70f1d8d968f374f09b395420901c0926a2d874f7/bin/node/runtime/src/lib.rs#L222)?

If your goal is to have a _simple_ system that gives tokens to block authors, you may want to write your own pallet that interfaces with `pallet_authorship` via its [`EventHandler`](https://substrate.dev/rustdocs/master/pallet_authorship/trait.EventHandler.html) trait rather than using staking (with all its stash/controller accounts, nominators, etc).

But if you do want to use the staking module, you have to be sure you're awarding points somehow.

**Comment by zikunfan** [comment]
Hi @JoshOrndorff,

Yes, I have alredy read the *rewards calculation*, but I am not familiar with `points mechanism` in staking module and `EventHandler` in the `authorship` pallet. I will read both of them. 

And there is any docs or tutorials I can read about the `points mechainism`?

**Comment by zikunfan** [comment]
Hi @JoshOrndorff,
I made it!😃 I import `authorship` pallet and using 

```rust
type EventHandler = (Staking, ImOnline)
```

and it can find block author&uncles now and get rewards! You really help me! i'm digging into more pallets now.

**Comment by JoshOrndorff** [comment]
Hooray! Glad you got it working :)
