### ISSUE TITLE
Adding contracts pallet to substrate-node-template per guide fails to compile

### ISSUE THREAD

**Issue by garrettmaring** [substrate-developer-hub/substrate-node-template#219]
**Description**

Using a bare substrate-node-template and adding https://substrate.dev/docs/en/tutorials/add-contracts-pallet/, compilation fails.

The docs suggest using two dependencies with 2021-05 tags. Using those seems incompatible with the existing dependencies of the template. Bumping them both to 2021-07 compiler with far fewer errors yet...

![Screen Shot 2021-07-21 at 6 54 57 PM](https://user-images.githubusercontent.com/8270120/126580563-df4551fa-3783-4fe0-a400-c858c5ffb6d4.png)

**Steps to Reproduce**

1. Clone this template
2. Go through https://substrate.dev/docs/en/tutorials/add-contracts-pallet/. It will fail at the first cargo check checkpoint.

**Expected vs. Actual Behavior**

Compile vs. compile error

**Environment**

macOS (M1) Big Sur 11.3.1

Default host: aarch64-apple-darwin
rustup home: /Users/.../.rustup

installed toolchains
stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

active toolchain
stable-aarch64-apple-darwin (default)
rustc 1.53.0 (53cb7b09b 2021-06-17)

**Comment by garrettmaring** [comment]
This error is also shown ![Screen Shot 2021-07-21 at 6 56 14 PM](https://user-images.githubusercontent.com/8270120/126580657-49e024b9-d141-4e07-a5af-026eb0f56d57.png)

**Comment by NukeManDan** [comment]
> You should already have version v3.0.0 of the Substrate Node Template compiled on your computer from when you completed the Create Your First Substrate Chain Tutorial. If you do not, please complete that tutorial.

The tutorials are expected to work with the tag specified: https://github.com/substrate-developer-hub/substrate-node-template/tree/v3.0.0
The snippets also [explicitly include the version](https://substrate.dev/docs/en/tutorials/add-contracts-pallet/#importing-the-contracts-pallet-crate)


Unfortunately, the resources to bring everything up to the latest monthly are lacking at the moment. Please try using uniform dependencies here,  or expect things to break (monthly substrate is not respecting semver).

This doesn't look to be caused by M1 ( #218 )but that may be a snag even with the right deps - let me know 🙏🏼

**Comment by garrettmaring** [comment]
I was caught between a rock and a hard place a bit trying to upgrade my substrate-node-template to support M1 yet then add back in the contracts pallets through the tutorial. I think I'll be able to finagle things into a working position.

**Comment by NukeManDan** [comment]
Any insights to share that are not already known to us here? Please do let us know 🙏🏼
