### ISSUE TITLE
ENABLE GITPOD PROJECT DEPENDENCIES SUPPORT

### ISSUE THREAD

**Issue by kcelestinomaria** [substrate-developer-hub/substrate-node-template#225]
**Motivation**

So, I find it extremely hard to run any node on my PC, I run everything on Gitpod, is there a way you could provide a gitpod.yml file and a gitpod.dockerfile file with the dependencies already set up so that it would be easy to just set up the project without having to keep on going over the same steps of downloading the needed dependencies for the project

**Suggested Solution**
Enable the dependencies needed on gitpod by default by creating a simple gitpod yml file. I am not sure the dependencies needed but they are simply the ones needed to run/compile a node on your local machine

_Describe your suggested solution to the need or frustration that you are experiencing._

**Alternatives**
 No other solutions I can come across. You guys created the Substrate Playground but it can't dynamically sync with a local repository, that is why gitpod is the current best option, will help newcomers as well when starting out.

_

**Comment by NukeManDan** [comment]
This was suggested a while back: https://github.com/inteurity/substrate-node-template-gitpod/

IIRC this us just a wrapper for a docker container run on gitpod servers plus an IDE, right? The issue was that their server instances are too low powered to build substrate, although the docker image with base build artifacts is nice. 

An arguably better alternative would be using the included docker files to build and deploy an image on a machine of higher capability. A good tool to help:
https://www.chevdor.com/post/2019/12/23/cargo-remote/
