### ISSUE TITLE
Node won't compile on Manjaro

### ISSUE THREAD

**Issue by marcocomo** [substrate-developer-hub/substrate-node-template#264]
**Description**

Just by following the guide on creating the first substrate blockchain, the code won't compile.

**Steps to Reproduce**

To reproduce simply follow the guide at https://docs.substrate.io/tutorials/v3/create-your-first-substrate-chain/

**Expected vs. Actual Behavior**

It should compile, instead what I did get is:

error: could not compile `libsecp256k1`

Caused by:
  process didn't exit successfully: `rustc --crate-name libsecp256k1 --edition=2018 /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/libsecp256k1-0.5.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="hmac"' --cfg 'feature="hmac-drbg"' --cfg 'feature="sha2"' --cfg 'feature="static-context"' --cfg 'feature="std"' --cfg 'feature="typenum"' -C metadata=ce39febbaf6e7ed7 -C extra-filename=-ce39febbaf6e7ed7 --out-dir /home/marco/substrate-node-template/target/release/deps -L dependency=/home/marco/substrate-node-template/target/release/deps --extern arrayref=/home/marco/substrate-node-template/target/release/deps/libarrayref-384acd6715054415.rmeta --extern base64=/home/marco/substrate-node-template/target/release/deps/libbase64-d6bebb368b603557.rmeta --extern digest=/home/marco/substrate-node-template/target/release/deps/libdigest-2291bab9e914ae63.rmeta --extern hmac_drbg=/home/marco/substrate-node-template/target/release/deps/libhmac_drbg-b50894fad1aa3acc.rmeta --extern libsecp256k1_core=/home/marco/substrate-node-template/target/release/deps/liblibsecp256k1_core-4ba4d60a1cc88e94.rmeta --extern rand=/home/marco/substrate-node-template/target/release/deps/librand-0bc232dad8d93af1.rmeta --extern serde=/home/marco/substrate-node-template/target/release/deps/libserde-4b9fcc9c10cf7fb0.rmeta --extern sha2=/home/marco/substrate-node-template/target/release/deps/libsha2-294b44da66cb6908.rmeta --extern typenum=/home/marco/substrate-node-template/target/release/deps/libtypenum-ae82346371e1b71a.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)

**Environment**

_Describe the environment in which you encountered this bug. Use the list below as a starting point
and add additional information if you think it's relevant._

- Operating system: Manjaro
- Template version/tag: Pahvo 21.1.6
- Rust version (run `rustup show`):
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)

Thanks in advance :)

**Comment by ming0109** [comment]
I have the same problem.

**Comment by ming0109** [comment]
I have the same problem.
My operating system is Ubuntu

The error is as follows:
error: could not compile `node-template`

Caused by:
  process didn't exit successfully: `rustc --crate-name node_template --edition=2018 node/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' -C metadata=6cc21c590d04f405 -C extra-filename=-6cc21c590d04f405 --out-dir /home/ubuntu/substrate-node-template/target/release/deps -L dependency=/home/ubuntu/substrate-node-template/target/release/deps --extern frame_benchmarking=/home/ubuntu/substrate-node-template/target/release/deps/libframe_benchmarking-043d71f8cb129541.rlib --extern frame_benchmarking_cli=/home/ubuntu/substrate-node-template/target/release/deps/libframe_benchmarking_cli-7f9531a3c50d3d04.rlib --extern jsonrpc_core=/home/ubuntu/substrate-node-template/target/release/deps/libjsonrpc_core-a3c917c5ba924dd1.rlib --extern node_template=/home/ubuntu/substrate-node-template/target/release/deps/libnode_template-31232c4f40c7290a.rlib --extern node_template_runtime=/home/ubuntu/substrate-node-template/target/release/deps/libnode_template_runtime-12585fa31dfb0e6e.rlib --extern pallet_transaction_payment_rpc=/home/ubuntu/substrate-node-template/target/release/deps/libpallet_transaction_payment_rpc-2c1440941a79be1a.rlib --extern sc_basic_authorship=/home/ubuntu/substrate-node-template/target/release/deps/libsc_basic_authorship-a7ca74ceadd5c26e.rlib --extern sc_cli=/home/ubuntu/substrate-node-template/target/release/deps/libsc_cli-dd655abe680512cc.rlib --extern sc_client_api=/home/ubuntu/substrate-node-template/target/release/deps/libsc_client_api-132eef8db9026ea0.rlib --extern sc_consensus=/home/ubuntu/substrate-node-template/target/release/deps/libsc_consensus-0a15e4494ec170fc.rlib --extern sc_consensus_aura=/home/ubuntu/substrate-node-template/target/release/deps/libsc_consensus_aura-49172e32ec239fd9.rlib --extern sc_executor=/home/ubuntu/substrate-node-template/target/release/deps/libsc_executor-2b1b26e41e5773b4.rlib --extern sc_finality_grandpa=/home/ubuntu/substrate-node-template/target/release/deps/libsc_finality_grandpa-ff956c754366e4ab.rlib --extern sc_keystore=/home/ubuntu/substrate-node-template/target/release/deps/libsc_keystore-07d50cfcda6b8bac.rlib --extern sc_rpc=/home/ubuntu/substrate-node-template/target/release/deps/libsc_rpc-a479e29b1403fd37.rlib --extern sc_rpc_api=/home/ubuntu/substrate-node-template/target/release/deps/libsc_rpc_api-1cd806941c49267e.rlib --extern sc_service=/home/ubuntu/substrate-node-template/target/release/deps/libsc_service-e5cf29f36b28676a.rlib --extern sc_telemetry=/home/ubuntu/substrate-node-template/target/release/deps/libsc_telemetry-f07e49f68b066496.rlib --extern sc_transaction_pool=/home/ubuntu/substrate-node-template/target/release/deps/libsc_transaction_pool-6c2db2733cbf3a15.rlib --extern sc_transaction_pool_api=/home/ubuntu/substrate-node-template/target/release/deps/libsc_transaction_pool_api-0e5206ee7c4ac661.rlib --extern sp_api=/home/ubuntu/substrate-node-template/target/release/deps/libsp_api-e1bd52b75ade678e.rlib --extern sp_block_builder=/home/ubuntu/substrate-node-template/target/release/deps/libsp_block_builder-23f186197b66e071.rlib --extern sp_blockchain=/home/ubuntu/substrate-node-template/target/release/deps/libsp_blockchain-403fba0697d3a1d5.rlib --extern sp_consensus=/home/ubuntu/substrate-node-template/target/release/deps/libsp_consensus-cce8e846e75bc243.rlib --extern sp_consensus_aura=/home/ubuntu/substrate-node-template/target/release/deps/libsp_consensus_aura-1af63525be4ab042.rlib --extern sp_core=/home/ubuntu/substrate-node-template/target/release/deps/libsp_core-c0b9433e643cd4e8.rlib --extern sp_finality_grandpa=/home/ubuntu/substrate-node-template/target/release/deps/libsp_finality_grandpa-3848e98ad38bdcc6.rlib --extern sp_runtime=/home/ubuntu/substrate-node-template/target/release/deps/libsp_runtime-5fec69f5be54cc28.rlib --extern sp_timestamp=/home/ubuntu/substrate-node-template/target/release/deps/libsp_timestamp-aed3b418b7887388.rlib --extern structopt=/home/ubuntu/substrate-node-template/target/release/deps/libstructopt-b59782a80f9407e2.rlib --extern substrate_frame_rpc_system=/home/ubuntu/substrate-node-template/target/release/deps/libsubstrate_frame_rpc_system-6ca6d9481faa4ea8.rlib -L native=/home/ubuntu/substrate-node-template/target/release/build/ring-a0be25830fdca0e5/out -L native=/home/ubuntu/substrate-node-template/target/release/build/libz-sys-50cbcc7676d2c490/out/lib -L native=/home/ubuntu/substrate-node-template/target/release/build/libz-sys-50cbcc7676d2c490/out/lib -L native=/home/ubuntu/substrate-node-template/target/release/build/zstd-sys-1ade408e2348c07e/out -L native=/home/ubuntu/substrate-node-template/target/release/build/psm-85beec52e9b48a0b/out -L native=/home/ubuntu/substrate-node-template/target/release/build/wasmtime-runtime-1687f739b7662fe0/out -L native=/home/ubuntu/substrate-node-template/target/release/build/librocksdb-sys-976f6768bdc69a6e/out -L native=/home/ubuntu/substrate-node-template/target/release/build/librocksdb-sys-976f6768bdc69a6e/out -L native=/home/ubuntu/substrate-node-template/target/release/build/lz4-sys-909231ab9a3ae296/out` (signal: 9, SIGKILL: kill)


My rust toolchain version:
ubuntu@ubuntu:~$ rustup show
Default host: aarch64-unknown-linux-gnu
rustup home:  /home/ubuntu/.rustup

installed toolchains
--------------------

stable-aarch64-unknown-linux-gnu (default)
nightly-2020-10-06-aarch64-unknown-linux-gnu
1.45.1-aarch64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-unknown-linux-gnu
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-unknown-linux-gnu (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)

**Comment by al3mart** [comment]
output of `rustup show` in my manjaro system

```
installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2020-10-05-x86_64-unknown-linux-gnu
nightly-2020-10-06-x86_64-unknown-linux-gnu
nightly-2020-10-25-x86_64-unknown-linux-gnu
nightly-2021-03-15-x86_64-unknown-linux-gnu
nightly-2021-08-22-x86_64-unknown-linux-gnu
nightly-2021-10-08-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.48.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.52.0 (88f19c6da 2021-05-03)

```

It compiles without problems. Check that you are not running our of memory

**Comment by al3mart** [comment]
This is the output of `rustup show` in my Manjaro system

```
installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

In compiles without problem.

Check that you are not running out of memory

**Comment by sacha-l** [comment]
I initially thought this could have been an issue with the node template version (latest is tagged to `'monthly-2021-10'` not `'monthly-2021-11-1`). But it builds and runs fine for me. Only difference with @al3mart is that I'm on macOS.

@marcocomo @ming0109 : did you manage to surmount this issue?

**Comment by marcocomo** [comment]
Nope, I tried and it's still not compiling. I also tried by following ths guide by parity [(here](https://www.parity.io/blog/how-to-build-your-own-blockchain-using-parity-substrate/) it doesn't work either.
