### ISSUE TITLE
Check all tutorial solutions compile with new `devhub/latest`

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-node-template#299]
This includes :  

- [x] Create your first chain tutorial 
- [ ] Permissioned-network: update to latest monthly
- [ ] Update forkless-upgrade tutorial to latest monthly 
- [ ] Private-network update to latest monthly 
- [ ] Node-metrics
- [ ] Nicks tutorial update to latest monthly 
- [ ] Kitties

**Comment by brunopgalvao** [comment]
Not sure if this is relevant but I noticed that the way we are storing the dependencies in the Cargo.toml file has changed in the substrate-node-template latest tag (see [here](https://github.com/substrate-developer-hub/substrate-node-template/blob/main/runtime/Cargo.toml)) which may throw off users who are following the tutorial. For example in the Nicks tutorial it asks the user to add this snippet:
````
[dependencies.pallet-nicks]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'devhub/latest'
version = '4.0.0-dev'
````
with the way the Cargo.toml file has been updated, the user has to add the dependency snippet after [line 51](https://github.com/substrate-developer-hub/substrate-node-template/blob/main/runtime/Cargo.toml#L51) otherwise it will not compile. For someone new to Rust, it may not be obvious that it needs to go after that line..

**Comment by NukeManDan** [comment]
I agree a docs update is needed - please open an issue there @brunopgalvao ? Should be trivial to implement... maybe even a PR to fix? :grin: 
I just updated the template again, and moved the tags to `polkadot-v0.9.17` FYI guys. Need to work of this moving forward. Should be no breaking changes AFAIK. #313 and #314

**Comment by NukeManDan** [comment]
@brunopgalvao cargo files are now using the one line format :)
