### ISSUE TITLE
why did you switch back to github dependencies from crates.io?

### ISSUE THREAD

**Issue by brenzi** [substrate-developer-hub/substrate-node-template#39]
For us this is undesirable. What is the reasoning behind moving backwards?

**Comment by brenzi** [comment]
I guess that's for @riusricardo , commit 6c1d11508cb8d3809e7b80606ce404ecfd5a85e4

**Comment by JoshOrndorff** [comment]
There are strengths to each approach. Personally I don't feel strongly either way, but I can answer the question.

When we pull alpha dependencies from crates.io like this:
```toml
sc-service = "2.0.0-alpha.6"
```

Semver thinks that an update to a newer alpha is compatible. So if someone clones our alpha.6 template, then decides to add a crate and specifies `2.0.0-alpha.6` as the version, cargo will notice that the crate was not previously in the `Cargo.lock` file. So cargo will pull the latest compatible version which it believes to be alpha.7. In reality, the alphas are not compatible and the build will break.

**Comment by brenzi** [comment]
yes, we have suffered from this cargo behaviour as well, but that can be solved by keeping the Cargo.lock file and avoid `cargo update`

**Comment by riusricardo** [comment]
That is correct and we also encourage the usage of a stable cargo.lock
I really look forward to use crates.io as the main source but versioning needs to improve to prevent this from happening often.
We may switch back to crates.io soon and we expect less breaking changes from now until we get v2.0.

The fact is that this repo is used along all of the tutorials. We need to keep them as stable as possible so people stay focused on learning Substrate instead of facing dependencies issues.

**Comment by JoshOrndorff** [comment]
> but that can be solved by keeping the Cargo.lock file and avoid cargo update

Consider if you add a new pallet to your runtime that wasn't included in the template and thus isn't in the cargo.lock file. Now you will have mostly alpha.6 and one alpha.7 (plus all the alpha.7 that that one pallet brought with it).
