### ISSUE TITLE
Accounts error

### ISSUE THREAD

**Issue by mustafasevinc** [substrate-developer-hub/substrate-node-template#40]
I installed Chain. "https://polkadot.js.org/apps/#/accounts" when I want to withdraw my accounts from this website "Uncaught error. Something went wrong with the query and rendering of this component. Cannot read property 'locks' of undefined "I'm getting this error.
There is no problem on other pages.

Substrate Node v2.0.0-alpha.7-e7f3167-x86_64-linux-gnu
api v1.14.0-beta.9
apps v0.42.0-beta.113

**Comment by adetante** [comment]
Yes, same error here. 
```
Uncaught TypeError: Cannot read property 'locks' of undefined
    at Account (main.28216c59.js:116349)
```

JS error occured at [this line in Account.tsx](https://github.com/polkadot-js/apps/blob/cd09733bb8faed38c09dba14d952a8309e97a64a/packages/page-accounts/src/Accounts/Account.tsx#L71).

I think it's because the `democracy` pallet is not present in the runtime of my node-template. As a workaround, I'll try to add [Democracy pallet](https://docs.rs/crate/pallet-democracy/2.0.0-alpha.7) to my runtime.

**Comment by JoshOrndorff** [comment]
Apps UI has merged https://github.com/polkadot-js/apps/pull/2726 which should fix this issue. Please try again and report back.

**Comment by mustafasevinc** [comment]
Yes, it was fixed. Thank you.
