### ISSUE TITLE
Two different peer id, for single node.

### ISSUE THREAD

**Issue by harsh-98** [substrate-developer-hub/substrate-node-template#52]
I was going through the `starting your own private network with https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-rc2`. I generated keys with subkey. Created chainspec, started node 1 and node2 . But node 2 failed with 

```
Error: Service(Network(The same bootnode (`/ip4/127.0.0.1/tcp/30333`) is registered with two different peer ids: `QmYkKnqtB46sufgYSPUBCFUdYn8ipvZ1H8jSDzvpMjx6wp` and `QmYb6raWsGsw5rpncKW2iJUBTxP3SdFy8KzjofaEtBAiJy`))
```

Id `QmYb6raWsGsw5rpncKW2iJUBTxP3SdFy8KzjofaEtBAiJy` was printed in logs of node1. But using it as bootnode peer id for node2 failed. Using `QmYkKnqtB46sufgYSPUBCFUdYn8ipvZ1H8jSDzvpMjx6wp` worked and I was successfully able to complete it.

Why is node1 printing a peer id and using another peer one?

**Comment by JoshOrndorff** [comment]
This is probably because your chain spec file contains one boot node address, but your bootnode itself advertises a different one. For this tutorial, there should not be any bootnodes in your chainspec file.

Please open your `customSpecRaw.json` file and look for a line like this near the top.
```json
"bootNodes": [],
```

If that list contains an actual bootnode, please remove it, and try again.

If you followed the tutorial _exactly_ you shouldn't end up in this situation because https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-rc2/customspec#create-a-chain-specification says to generate your custom spec using this command.
```bash
# Export the local chainspec to json
$ ./target/release/node-template build-spec --disable-default-bootnode --chain local > customSpec.json
```

When you include `--disable-default-bootnode` as demonstrated, your spec file does not include that bootnode address.

**Comment by harsh-98** [comment]
Yup, thanks.

**Comment by rvganisa** [comment]
Hi, I do have similar issue with the following error:
error: Invalid value for '--bootnodes <ADDR>...': invalid multiaddr

Can assist on this issue?

Thank you

**Comment by danforbes** [comment]
Can you describe what are you doing when you encounter this error? Were you working with chain specs? If so, how did you generate them?
