### ISSUE TITLE
Release process enhancement: Make a github release

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-node-template#72]
![Screenshot 2020-08-14 at 13 07 16](https://user-images.githubusercontent.com/898091/90216438-11b41600-de31-11ea-8f35-83c70caa03ca.png)

It seems Github regards the `v2.0.0-alpha.5` as the "canonical" latest release. Clicking inside [releases](https://github.com/substrate-developer-hub/substrate-node-template/releases), `v2.0.0-alpha.5` is being emphasized. 

Let's tell github our latest one is `rc5`.

**Comment by JoshOrndorff** [comment]
I've made the rc5 release and it now shows on the github page. The issue was that the we had _tagged_ `v2.0.0-rc5`, but not created a github release. If we value that tab on the right side (and IMO we do) we need to do this additional step of creating a github release each time.

@danforbes wasn't there some doc that wrote up the release process somewhere? I'm not seeing it in this repo. In fact I don't even see contributing guidelines or the instructions for cutting a template from a specific upstream commit anymore.

**Comment by danforbes** [comment]
That is an internal doc, Joshy - I will share it with you privately. Personally, I do not see the value in maintaining releases for this project - it is a code template that is meant to be forked and used to create a new application; it is not an application itself.

**Comment by JoshOrndorff** [comment]
We agreed to delete all existing releases and rely on pure `git` tags instead.
