### ISSUE TITLE
What commands to build the node template?

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-node-template#93]
I'm trying to build the node template. I checkout the latest code on master (`5dc7853`) and run `cargo check`. It fails with

```
  Rust WASM toolchain not installed, please install it!

  Further error information:
  ------------------------------------------------------------
     Compiling wasm-test v1.0.0 (/tmp/.tmpEGpa1b)
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `wasm-test`

  To learn more, run the command again with --verbose.
  ------------------------------------------------------------

warning: build failed, waiting for other jobs to finish...
```

I also tried `cargo build --release` as suggested in the readme, but it fails with the less verbose
```
Rust WASM toolchain not installed, please install it!
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I suspect this is related to #92 , but not sure.

**Comment by riusricardo** [comment]
Try:
```
rustup install nightly-2020-10-06
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
```
```
cargo +nightly-2020-10-06 build --release
```

**Comment by JoshOrndorff** [comment]
Yeah, those suggestions worked @riusricardo 

I wonder if that should go in the Readme.

**Comment by danforbes** [comment]
Because we decided not to include set up instructions in this repo but instead include them as part of the Knowledge Base, this is currently being approached by having a toolchain file in this repo and a note in the Knowledge Base here https://substrate.dev/docs/en/knowledgebase/getting-started/#rust-nightly-toolchain. I'm open to considering other approaches, but with respect to this particular Issue I would prefer to close it if you have gotten over your specific problem, Joshy.
